// console.log("hello shivendra");
let gggName = "shivendra";
// console.log(gggName);
const Id = 89;
// console.log(Id);
let mine = "new one";
let name = "JDJD";
let see = "sss&";
// console.log(see);
// console.log(name);
let num1 = 45;
let num2 = 56;
let bool1 = true;
let bool2 = false;
console.log(Boolean(100));
console.log(Boolean(0));
console.log(Boolean(''));
console.log(Boolean(' '));
console.log(Boolean(null));
console.log(Boolean(undefined));
console.log(Boolean(false));
console.log(Boolean("false"));
console.log(Boolean('0'));
console.log(Boolean('null'));
console.log(Boolean('undefined'));
export {};
//}) ()
